#ifndef ERROR_H_INCLUDED
#define ERROR_H_INCLUDED

#include <stdio.h>

typedef enum PSX_ERROR {
    NO_ERROR,
    // PSX
    INSUFFICIENT_ARGS,
    // CPU
    CPU_FETCH_ERROR,
    CPU_DECODE_ERROR,
    CPU_EXECUTE_ERROR,
    // INSTRUCTIONS
    RTYPE_ERROR,
    ITYPE_ERROR,
    JTYPE_ERROR,
    UNKNOWN_OPCODE,
    
    // MEMORY
    BIOS_FILE_NOT_FOUND,
    BIOS_FILE_UNREADABLE,
    MEMORY_CPU_UNMAPPED_ADDRESS,
} PSX_ERROR;

#endif//ERROR_H_INCLUDED
