#ifndef ERROR_H_INCLUDED
#define ERROR_H_INCLUDED

#include "common.h"

typedef enum PSX_ERROR {
  NO_ERROR,
  // MEMORY
  BIOS_FILE_NOT_FOUND,
  BIOS_FILE_UNREADABLE,
  MEMORY_KUSEG_UNMAPPED_ADDRESS,
  MEMORY_KSEG0_UNMAPPED_ADDRESS,
  MEMORY_KSEG1_UNMAPPED_ADDRESS,
  
} PSX_ERROR;

#endif//ERROR_H_INCLUDED
